export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ADD_ITEMS = 'ADD_ITEMS';
export const ITEMS_FAILED = 'ITEMS_FAILED';

export const PC_MAKING_LOADING = 'PC_MAKING_LOADING';
export const ADD_PC_MAKING = 'ADD_PC_MAKING';
export const PC_MAKING_FAILED = 'PC_MAKING_FAILED';

export const ORDERS_LOADING = 'ORDERS_LOADING';
export const ADD_ORDERS = 'ADD_ORDERS';
export const ORDERS_FAILED = 'ORDERS_FAILED';